#FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04
FROM nvidia/cuda:13.0.1-cudnn-devel-ubuntu22.04
############################## SYSTEM PARAMETERS ##############################
# * Arguments
ARG USER=initial
ARG GROUP=initial
ARG UID=1000
ARG GID="${UID}"
ARG SHELL=/bin/bash
ARG HARDWARE=x86_64
ARG ENTRYPOINT_FILE=entrypint.sh

# * Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
# ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

# * Setup users and groups
RUN groupadd -g ${GID} ${USER} \
    && useradd -m -u ${UID} -g ${GID} -s ${SHELL} ${USER} \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        sudo \
        git \
        wget \
        vim \
        python3-pip \
        python3-dev \
        build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER}


# * Replace apt urls
# ? Change to tku
RUN sed -i 's@archive.ubuntu.com@ftp.tku.edu.tw@g' /etc/apt/sources.list
# ? Change to Taiwan
# RUN sed -i 's@archive.ubuntu.com@tw.archive.ubuntu.com@g' /etc/apt/sources.list

# * Time zone
ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/"${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone

# * Copy custom configuration
# ? Requires docker version >= 17.09
COPY --chmod=0775 ./${ENTRYPOINT_FILE} /entrypoint.sh
COPY --chown="${USER}":"${GROUP}" --chmod=0775 config config
# ? docker version < 17.09
# COPY ./${ENTRYPOINT_FILE} /entrypoint.sh
# COPY config config
# RUN sudo chmod 0775 /entrypoint.sh && \
    # sudo chown -R "${USER}":"${GROUP}" config \
    # && sudo chmod -R 0775 config

############################### INSTALL #######################################
# * Install packages
RUN apt update \
    && apt install -y --no-install-recommends \
        sudo \
        git \
        htop \
        wget \
        curl \
        psmisc \
        # * Shell
        tmux \
        terminator \
        # * base tools
        udev \
        libtool \
        python3-pip \
        python3-dev \
        python3-setuptools \
        software-properties-common \
        lsb-release \
        # * Work tools
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# gnome-terminal libcanberra-gtk-module libcanberra-gtk3-module \
# dbus-x11 libglvnd0 libgl1 libglx0 libegl1 libxext6 libx11-6 \
# display dep
# libnss3 libgbm1 libxshmfence1 libdrm2 libx11-xcb1 libxcb-*-dev

# ENV DEBIAN_FRONTEND=noninteractive


RUN ./config/pip/pip_setup.sh
# Install pip
RUN pip3 install --upgrade pip \
    && pip3 install setuptools \
    && pip3 install wheel \
    && pip3 install nvitop \
    && pip3 install notebook

# RUN sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
# RUN sudo add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u
# RUN rm -rf /etc/apt/source.list.d/ros2.list
RUN export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(lsb_release -c | awk '{print $2}')_all.deb" && \
    dpkg -i /tmp/ros2-apt-source.deb && \
    rm /tmp/ros2-apt-source.deb
RUN apt update && apt install -y --no-install-recommends \
    ros-humble-desktop \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-diagnostic-updater \
    ros-humble-moveit \
    python3-colcon-common-extensions \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists 

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE

RUN add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u

RUN apt-get update && apt-get install -y --no-install-recommends \
    librealsense2-utils \
    librealsense2-dev \
    librealsense2-udev-rules \ 
    && apt-get clean && rm -rf /var/lib/apt/lists/*c


RUN apt-get update && apt-get install -y --no-install-recommends \
    v4l-utils \
    ffmpeg \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-ur \
    ros-humble-xacro \
    ros-humble-ros-testing

# * Install miniconda
ENV CONDA_DIR=/home/"${USER}"/miniconda3
RUN mkdir -p ${CONDA_DIR} \
    && wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${CONDA_DIR}/miniconda.sh \
    && bash ${CONDA_DIR}/miniconda.sh -b -u -p ${CONDA_DIR} \
    && rm ${CONDA_DIR}/miniconda.sh

ENV PATH=${CONDA_DIR}/bin:$PATH
RUN chown -R "${UID}:${GID}" "${CONDA_DIR}"


############################## USER CONFIG ####################################
# * Switch user to ${USER}
USER ${USER}

RUN ./config/shell/bash_setup.sh "${USER}" "${GROUP}" \
    && ./config/shell/terminator/terminator_setup.sh "${USER}" "${GROUP}" \
    && ./config/shell/tmux/tmux_setup.sh "${USER}" "${GROUP}" \
    && sudo rm -rf /config
RUN export CXX=g++
RUN export MAKEFLAGS="-j nproc"
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
RUN echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> ~/.bashrc



WORKDIR /home/${USER}/work
####create lidpm conda env
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main \
    && conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
RUN conda create -n lidpm python=3.10 -y
RUN conda init


RUN conda run -n lidpm pip install torch torchvision --index-url https://download.pytorch.org/whl/cu130
RUN git clone https://github.com/AzharSindhi/MinkowskiEngineCuda13.git

WORKDIR /home/${USER}/work/MinkowskiEngineCuda13
RUN sudo apt install -y build-essential libopenblas-dev
RUN conda run -n lidpm pip install ninja tqdm click six
RUN export CUDA_HOME=$CONDA_PREFIX && \
    export TORCH_CUDA_ARCH_LIST='12.0+PTX' && \
    export CPLUS_INCLUDE_PATH=/usr/local/cuda/include/cccl:$CPLUS_INCLUDE_PATH && \
    export C_INCLUDE_PATH=/usr/local/cuda/include/cccl:$C_INCLUDE_PATH && \
    export CPATH=/usr/local/cuda/include/cccl:$CPATH && \
    conda run -n lidpm python setup.py install --blas=openblas --force_cuda
RUN conda run -n lidpm pip install open3d natsort


#open3d                    0.19.0
#ninja                     1.13.0
#tqdm                      4.67.3
#click                     8.3.1
#six                       1.17.0
#natsort                   8.4.0
#torch                     2.10.0+cu130
#torchvision               0.25.0+cu130



# * Switch workspace to ~/work
RUN mkdir -p /home/"${USER}"/work
WORKDIR /home/"${USER}"/work

    
# * Make SSH available
EXPOSE 22

ENTRYPOINT [ "/entrypoint.sh", "terminator" ]
# ENTRYPOINT [ "/entrypoint.sh", "tmux" ]
# ENTRYPOINT [ "/entrypoint.sh", "bash" ]
# ENTRYPOINT [ "/entrypoint.sh" ]
